package io.github.scala_tessella.dcel

import io.github.scala_tessella.dcel.TilingCertifier.{
  Certified, RejectReason, certify, innerVertexTypes, vertexTypeOf
}
import io.github.scala_tessella.dcel.VertexTypes.*
import io.github.scala_tessella.dcel.geometry.{AngleDegree, BigPoint, RegularPolygon}
import io.github.scala_tessella.ring_seq.RingSeq.startAt

import scala.collection.mutable

/** Fixed-Λ enumeration engine for the Krotenheerdt tilings (OEIS A068600), the scalable replacement for the
  * patch-growth search (ADR-0018). Instead of growing aperiodic patches and rejecting them at certification,
  * it enumerates candidate translation lattices Λ from a bounded set and, for each fixed Λ, grows only
  * Λ-consistent patches ([[LatticeConsistency]]): off-lattice "decoration" placements are pruned at the
  * branch point, so the scatter is never built. The per-Λ search is tiny, so the cost scales to higher n.
  *
  * Soundness is by construction — every produced tiling is certified periodic and n-uniform by the existing
  * [[TilingCertifier.certify]]. Completeness rests on the candidate set including every true lattice: the
  * vertices of a regular-polygon tiling lie in the module ℤ[ζ₁₂] (30° directions, plus ℤ[ζ₈] 45° directions
  * for the octagon's 4.8.8), and every translation period is itself such a vector, so a step-bounded
  * enumeration of that module — with the bound K verified per n by reproducing the published count — contains
  * them all.
  */
object KrotenheerdtLatticeSearch:

  final case class Outcome(certified: List[Certified], basesTried: Int, statesExplored: Long)

  // Candidate lattices are enumerated in Double — exact BigDecimal arithmetic on arbitrary module points
  // makes gaussReduced explode in precision and hang; the candidates only need ~1e-12 accuracy (the oracle
  // and certify recompute everything precisely), so Double is both correct enough and fast.
  private type P = (Double, Double)

  /** Unit vectors at multiples of `step` degrees. */
  private def unit(stepDegrees: Int): P =
    val r = math.toRadians(stepDegrees)
    (math.cos(r), math.sin(r))

  // ℤ[ζ₁₂] is generated by unit steps at 0,30,60,90°; ℤ[ζ₈] (octagon) by 0,45,90,135°.
  private val generators12 = List(0, 30, 60, 90).map(unit)
  private val generators8  = List(0, 45, 90, 135).map(unit)

  private def dot(a: P, b: P): Double   = a._1 * b._1 + a._2 * b._2
  private def cross(a: P, b: P): Double = a._1 * b._2 - a._2 * b._1
  private def keyD(p: P): (Long, Long)  = (math.round(p._1 * 1e6), math.round(p._2 * 1e6))
  private def neg(p: P): P              = (-p._1, -p._2)
  private def canonicalSign(p: P): P    =
    if p._2 > 1e-9 || (math.abs(p._2) <= 1e-9 && p._1 > 0) then p else neg(p)

  /** Lagrange–Gauss reduction of a 2D basis to the two successive minima. Stops when `b` is reduced against
    * `a` (2|a·b| ≤ |a|²); the strict-plus-epsilon condition keeps equal-length 60° pairs (where `round(0.5)`
    * would otherwise over-reduce and oscillate) from looping, and an iteration cap is a float safety net.
    */
  private def gaussReduceD(v0: P, w0: P): (P, P) =
    var a    = v0
    var b    = w0
    if dot(a, a) > dot(b, b) then { val t = a; a = b; b = t }
    var iter = 0
    while iter < 10_000 && 2 * math.abs(dot(a, b)) > dot(a, a) + 1e-9 do
      val m = math.round(dot(a, b) / dot(a, a)).toDouble
      b = (b._1 - m * a._1, b._2 - m * a._2)
      if dot(a, a) > dot(b, b) then { val t = a; a = b; b = t }
      iter += 1
    (a, b)

  /** Module points reachable within integer step-count `k` over the given generators (and their negatives).
    */
  private def modulePoints(generators: List[P], k: Int): List[P] =
    val seen                                              = mutable.LinkedHashMap.empty[(Long, Long), P]
    def go(remaining: List[P], budget: Int, acc: P): Unit =
      remaining match
        case Nil     => seen.getOrElseUpdate(keyD(acc), acc)
        case g :: gs =>
          for c <- -budget to budget do go(gs, budget - math.abs(c), (acc._1 + c * g._1, acc._2 + c * g._2))
    go(generators, k, (0.0, 0.0))
    seen.values.toList

  /** A fundamental cell holds at least one polygon, so its covolume is at least the smallest face area (a
    * unit triangle, √3/4 ≈ 0.433). The dense rank-4 module otherwise yields infinitely many spurious
    * tiny-covolume lattices; this floor removes them. The ceiling bounds the largest cell to enumerate.
    */
  private val minCovolume = 0.4

  /** Candidate primitive bases within step bound `k` and covolume in `[minCovolume, maxCovolume]`, Gauss-
    * reduced, sign-canonicalised, deduped, ordered by covolume (smallest fundamental cell first). Includes
    * the octagon (45°) module when `withOctagon`.
    */
  def candidateBases(k: Int, maxCovolume: Double, withOctagon: Boolean = false): List[(BigPoint, BigPoint)] =
    val points =
      (modulePoints(generators12, k) ++ (if withOctagon then modulePoints(generators8, k) else Nil))
        .filter(p => math.hypot(p._1, p._2) > 1e-6)
    val byKey  = mutable.LinkedHashMap.empty[((Long, Long), (Long, Long)), (P, P)]
    for
      i   <- points.indices
      j   <- (i + 1) until points.size
      area = math.abs(cross(points(i), points(j)))
      if area >= minCovolume && area <= maxCovolume + 1e-9
    do
      val (a, b) = gaussReduceD(points(i), points(j))
      val cov    = math.abs(cross(a, b))
      if cov >= minCovolume - 1e-9 && cov <= maxCovolume + 1e-9 then
        val (ca, cb) = (canonicalSign(a), canonicalSign(b))
        val ord      = Ordering[(Double, (Long, Long))]
        val pair     =
          if ord.lteq((dot(ca, ca), keyD(ca)), (dot(cb, cb), keyD(cb))) then (ca, cb) else (cb, ca)
        byKey.getOrElseUpdate((keyD(pair._1), keyD(pair._2)), pair)
    byKey.values.toList
      .sortBy((v, w) => (math.abs(cross(v, w)), dot(v, v) + dot(w, w)))
      .map((v, w) =>
        (BigPoint(BigDecimal(v._1), BigDecimal(v._2)), BigPoint(BigDecimal(w._1), BigDecimal(w._2)))
      )

  /** Enumerate all Krotenheerdt n-uniform tilings via fixed-Λ growth over candidate bases up to step bound k.
    */
  def enumerate(
      n: Int,
      k: Int,
      maxCovolume: Double,
      parallelism: Int = 1,
      log: String => Unit = _ => ()
  ): Outcome =
    import java.util.concurrent.ConcurrentHashMap
    import java.util.concurrent.atomic.AtomicLong
    import scala.jdk.CollectionConverters.*

    val bases  = candidateBases(k, maxCovolume, withOctagon = n == 1)
    val found  = new ConcurrentHashMap[String, Certified]()
    val states = new AtomicLong(0)
    val done   = new AtomicLong(0)
    val capped = new AtomicLong(0)
    val perCap = 5000
    log(s"n=$n k=$k maxCovol=$maxCovolume: ${bases.size} candidate lattices")

    def runLattice(v: BigPoint, w: BigPoint): Unit =
      val covol   = v.cross(w).abs
      val visited = mutable.HashSet.empty[List[(Int, BigDecimal, BigDecimal)]]
      val stack   = mutable.Stack.empty[Tiling]
      var local   = 0
      polygonSides.foreach: sides =>
        val seed = TilingBuilder.createRegularPolygon(RegularPolygon(sides))
        if LatticeConsistency.isConsistent(seed, v, w, seed.vertices.head.coords) then stack.push(seed)
      while stack.nonEmpty && local < perCap do
        val patch  = stack.pop()
        states.incrementAndGet()
        local += 1
        val origin = patch.vertices.head.coords
        val area   = patch.innerFaces.map(_.areaUnsafe).sum
        // certify needs the witness cell's corona deep-interior (~5x5 cells), so trigger only once the patch
        // is that big; the oracle makes growth deterministic past the first cell, so there is no scatter to
        // retry through. Grow further only while still too small.
        if area >= covol * 25 then
          certify(patch, n) match
            case Right(c) =>
              found.putIfAbsent(c.torusKey, c)
            case Left(r)
                if (r == RejectReason.NoLattice || r == RejectReason.BlockTooSmall ||
                  r == RejectReason.NoWitnessCell || r == RejectReason.TooShallow) && area < covol * 64 =>
              grow(patch, v, w, origin, n, visited, stack)
            case Left(_)  => ()
        else grow(patch, v, w, origin, n, visited, stack)
      if local >= perCap then capped.incrementAndGet()
      val d       = done.incrementAndGet()
      if d % 2000 == 0 then
        log(s"  lattices ${d}/${bases.size}, states=${states.get}, found=${found.size}, capped=${capped.get}")

    if parallelism <= 1 then bases.foreach(runLattice)
    else
      val pool = java.util.concurrent.Executors.newFixedThreadPool(parallelism)
      try bases.foreach((v, w) => pool.submit(new Runnable { def run(): Unit = runLattice(v, w) }))
      finally
        pool.shutdown()
        pool.awaitTermination(7, java.util.concurrent.TimeUnit.DAYS)
    log(s"  capped lattices (hit ${perCap} states): ${capped.get}")

    Outcome(found.values.asScala.toList.sortBy(_.torusKey), bases.size, states.get)

  /** Push every Λ-consistent, sound continuation that fills the centroid-nearest boundary gap. */
  private def grow(
      patch: Tiling,
      v: BigPoint,
      w: BigPoint,
      origin: BigPoint,
      n: Int,
      visited: mutable.HashSet[List[(Int, BigDecimal, BigDecimal)]],
      stack: mutable.Stack[Tiling]
  ): Unit =
    val gaps     = patch.boundaryVerticesUnsafe.flatMap: vertex =>
      val gap = AngleDegree(360) - vertex.currentInteriorAngleSumUnsafe(patch.outerFace)
      Option.when(gap.toRational > 0)((vertex, gap))
    val centroid = patch.vertices.map(_.coords).centroid
    gaps.minByOption((vertex, gap) =>
      (vertex.coords.distanceTo(centroid), gap.toRational, vertex.id.value)
    ).foreach: (target, gap) =>
      val previousInnerIds = patch.innerVertices.map(_.id).toSet
      polygonSides.foreach: sides =>
        if interiorAngle(sides).toRational <= gap.toRational then
          patch
            .maybeAddRegularPolygonToBoundary(target.id, RegularPolygon(sides))
            .toOption
            .filter(next =>
              isSound(next, previousInnerIds, n) && LatticeConsistency.isConsistent(next, v, w, origin)
            )
            .foreach: next =>
              if visited.add(PatchCanonical.congruenceKey(next)) then stack.push(next)

  private def isSound(next: Tiling, previousInnerIds: Set[structure.VertexId], n: Int): Boolean =
    val newInnerValid =
      next.innerVertices
        .filterNot(v => previousInnerIds.contains(v.id))
        .forall(v => isCompleteVertex(vertexTypeOf(next, v)))
    val fansValid     =
      next.boundaryVerticesUnsafe.forall: vertex =>
        boundaryFan(next, vertex) match
          case Nil => true
          case fan => isExtendableFan(fan)
    next.hasUnitRegularPolygonsOnly && newInnerValid && fansValid && innerVertexTypes(next).sizeIs <= n

  private def boundaryFan(tiling: TilingDCEL, vertex: structure.Vertex): List[Int] =
    val edges      = vertex.incidentEdgesUnsafe
    val outerIndex = edges.indexWhere(_.incidentFace.exists(_ eq tiling.outerFace))
    val ordered    = if outerIndex < 0 then edges else edges.startAt(outerIndex).tail
    ordered.flatMap(_.incidentFace).filter(_ != tiling.outerFace).map(_.halfEdgesUnsafe.size)
