package io.github.scala_tessella.dcel

import io.github.scala_tessella.dcel.TilingCertifier.{innerVertexTypes, vertexTypeOf}
import io.github.scala_tessella.dcel.VertexTypes.*
import io.github.scala_tessella.dcel.geometry.{AngleDegree, BigPoint, RegularPolygon}
import io.github.scala_tessella.ring_seq.RingSeq.startAt

import scala.collection.mutable

/** Fixed-Λ enumeration engine for the Krotenheerdt tilings (OEIS A068600), the scalable replacement for the
  * patch-growth search (ADR-0018). Instead of growing aperiodic patches and rejecting them at certification,
  * it enumerates candidate translation lattices Λ from a bounded set and, for each fixed Λ, grows only
  * Λ-consistent patches ([[LatticeConsistency]]): off-lattice "decoration" placements are pruned at the
  * branch point, so the scatter is never built. The per-Λ search is tiny, so the cost scales to higher n.
  *
  * Each fixed-Λ patch that tiles one fundamental cell is verified directly on the torus ([[verifyTorus]]):
  * the distinct faces tile one covolume, every torus vertex has a complete 360° fan (reconstructed by
  * unioning the partial coronas of all its planar instances, keyed by angle), the vertex types equal n, and
  * the vertex ORBITS equal n — counted exactly ([[vertexOrbits]]), not by 1-WL colour refinement, which only
  * lower-bounds the orbit count and would pass a >n-uniform tiling as n-uniform. Completeness rests on the
  * candidate set including every true lattice: the vertices of a regular-polygon tiling lie in the module
  * ℤ[ζ₁₂] (30° directions, plus ℤ[ζ₈] 45° directions for the octagon's 4.8.8), and every translation period
  * is itself such a vector, so a step-bounded enumeration of that module — with the bound k verified per n by
  * reproducing the published count — contains them all.
  *
  * STATUS (see ADR-0019): SOUND — every tiling reported is a genuine Krotenheerdt n-uniform tiling with the
  * correct multiplicity. Multi-vertex cells (6.6.6, the snub 3.3.3.3.6), sublattice deduplication, and the
  * up-to-all-isometries chirality convention all work; validated with no false positives against n=1 (10 of
  * 11 Archimedean tilings) and n=2 (16 of the 20). Completeness is bounded by the empirical
  * `(k, maxCovolume)` — the few missing tilings are the largest dodecagon cells (4.6.12), reached only at a
  * larger step bound k. The original [[KrotenheerdtSearch]] remains the reference engine that rigorously
  * enumerated n ≤ 2.
  */
object KrotenheerdtLatticeSearch:

  final case class Outcome(
      tilings: List[(Set[VertexSignature], String)],
      basesTried: Int,
      statesExplored: Long
  )

  // Candidate lattices are enumerated in Double — exact BigDecimal arithmetic on arbitrary module points
  // makes Gauss reduction explode in precision and hang; the candidates only need ~1e-12 accuracy (the
  // oracle and verifyTorus recompute everything precisely at SCALE 9), so Double is both correct and fast.
  private type P = (Double, Double)

  /** Unit vectors at multiples of `step` degrees. */
  private def unit(stepDegrees: Int): P =
    val r = math.toRadians(stepDegrees)
    (math.cos(r), math.sin(r))

  // ℤ[ζ₁₂] is generated by unit steps at 0,30,60,90°; ℤ[ζ₈] (octagon) by 0,45,90,135°.
  private val generators12 = List(0, 30, 60, 90).map(unit)
  private val generators8  = List(0, 45, 90, 135).map(unit)

  private def dot(a: P, b: P): Double   = a._1 * b._1 + a._2 * b._2
  private def cross(a: P, b: P): Double = a._1 * b._2 - a._2 * b._1
  private def keyD(p: P): (Long, Long)  = (math.round(p._1 * 1e6), math.round(p._2 * 1e6))
  private def neg(p: P): P              = (-p._1, -p._2)
  private def canonicalSign(p: P): P    =
    if p._2 > 1e-9 || (math.abs(p._2) <= 1e-9 && p._1 > 0) then p else neg(p)

  /** Lagrange–Gauss reduction of a 2D basis to the two successive minima. Stops when `b` is reduced against
    * `a` (2|a·b| ≤ |a|²); the strict-plus-epsilon condition keeps equal-length 60° pairs (where `round(0.5)`
    * would otherwise over-reduce and oscillate) from looping, and an iteration cap is a float safety net.
    */
  private def gaussReduceD(v0: P, w0: P): (P, P) =
    var a    = v0
    var b    = w0
    if dot(a, a) > dot(b, b) then { val t = a; a = b; b = t }
    var iter = 0
    while iter < 10_000 && 2 * math.abs(dot(a, b)) > dot(a, a) + 1e-9 do
      val m = math.round(dot(a, b) / dot(a, a)).toDouble
      b = (b._1 - m * a._1, b._2 - m * a._2)
      if dot(a, a) > dot(b, b) then { val t = a; a = b; b = t }
      iter += 1
    (a, b)

  /** Lagrange–Gauss reduction of a `BigPoint` basis via Double arithmetic. The shared exact-`BigDecimal`
    * `TilingLattice.gaussReduced` explodes in precision — and can fail to terminate (its loop only stops when
    * the integer multiplier rounds to exactly 0) — on the messy centroid-difference vectors fed to
    * [[primitiveBasis]]. The reduced basis only canonicalises the torus key, which recomputes coordinates at
    * SCALE 9, so Double precision is sufficient and safe.
    */
  private def gaussReducedSafe(a: BigPoint, b: BigPoint): (BigPoint, BigPoint) =
    val (ra, rb) = gaussReduceD((a.x.toDouble, a.y.toDouble), (b.x.toDouble, b.y.toDouble))
    (BigPoint(BigDecimal(ra._1), BigDecimal(ra._2)), BigPoint(BigDecimal(rb._1), BigDecimal(rb._2)))

  /** Module points reachable within integer step-count `k` over the given generators (and their negatives).
    */
  private def modulePoints(generators: List[P], k: Int): List[P] =
    val seen                                              = mutable.LinkedHashMap.empty[(Long, Long), P]
    def go(remaining: List[P], budget: Int, acc: P): Unit =
      remaining match
        case Nil     => seen.getOrElseUpdate(keyD(acc), acc)
        case g :: gs =>
          for c <- -budget to budget do go(gs, budget - math.abs(c), (acc._1 + c * g._1, acc._2 + c * g._2))
    go(generators, k, (0.0, 0.0))
    seen.values.toList

  /** A fundamental cell holds at least one polygon, so its covolume is at least the smallest face area (a
    * unit triangle, √3/4 ≈ 0.433). The dense rank-4 module otherwise yields infinitely many spurious
    * tiny-covolume lattices; this floor removes them. The ceiling bounds the largest cell to enumerate.
    */
  private val minCovolume = 0.4

  // Unit-edge polygon areas {3,4,6,8,12}. A fundamental cell is a whole number of polygons, so its covolume
  // is a non-negative integer combination of these — a sparse set. Filtering candidate covolumes to it drops
  // the dense module's spurious lattices (whose covolume is an arbitrary real) by a large factor.
  private val polygonAreas = List(3, 4, 6, 8, 12).map(s => s / (4.0 * math.tan(math.Pi / s)))

  private def achievableCovolumes(maxCovolume: Double): Set[Double] =
    val reached  = mutable.Set(0.0)
    var frontier = List(0.0)
    while frontier.nonEmpty do
      frontier = frontier.flatMap: c =>
        polygonAreas.map(c + _).filter(s => s <= maxCovolume + 1e-6 && reached.add(s))
    reached.filter(_ >= minCovolume - 1e-6).toSet

  private def isAchievable(covol: Double, achievable: Set[Double]): Boolean =
    achievable.exists(a => math.abs(a - covol) < 1e-6)

  /** Candidate primitive bases within step bound `k` and covolume in `[minCovolume, maxCovolume]`, Gauss-
    * reduced, sign-canonicalised, deduped, ordered by covolume (smallest fundamental cell first). Includes
    * the octagon (45°) module when `withOctagon`.
    */
  def candidateBases(k: Int, maxCovolume: Double, withOctagon: Boolean = false): List[(BigPoint, BigPoint)] =
    val achievable = achievableCovolumes(maxCovolume)
    val points     =
      (modulePoints(generators12, k) ++ (if withOctagon then modulePoints(generators8, k) else Nil))
        .filter(p => math.hypot(p._1, p._2) > 1e-6)
    val byKey      = mutable.LinkedHashMap.empty[((Long, Long), (Long, Long)), (P, P)]
    for
      i   <- points.indices
      j   <- (i + 1) until points.size
      area = math.abs(cross(points(i), points(j)))
      if area >= minCovolume && area <= maxCovolume + 1e-9
    do
      val (a, b) = gaussReduceD(points(i), points(j))
      val cov    = math.abs(cross(a, b))
      if cov >= minCovolume - 1e-9 && cov <= maxCovolume + 1e-9 && isAchievable(cov, achievable) then
        val (ca, cb) = (canonicalSign(a), canonicalSign(b))
        val ord      = Ordering[(Double, (Long, Long))]
        val pair     =
          if ord.lteq((dot(ca, ca), keyD(ca)), (dot(cb, cb), keyD(cb))) then (ca, cb) else (cb, ca)
        byKey.getOrElseUpdate((keyD(pair._1), keyD(pair._2)), pair)
    byKey.values.toList
      .sortBy((v, w) => (math.abs(cross(v, w)), dot(v, v) + dot(w, w)))
      .map((v, w) =>
        (BigPoint(BigDecimal(v._1), BigDecimal(v._2)), BigPoint(BigDecimal(w._1), BigDecimal(w._2)))
      )

  /** Enumerate all Krotenheerdt n-uniform tilings via fixed-Λ growth over candidate bases up to step bound k.
    */
  def enumerate(
      n: Int,
      k: Int,
      maxCovolume: Double,
      parallelism: Int = 1,
      log: String => Unit = _ => ()
  ): Outcome =
    import java.util.concurrent.ConcurrentHashMap
    import java.util.concurrent.atomic.AtomicLong
    import scala.jdk.CollectionConverters.*

    val bases       = candidateBases(k, maxCovolume, withOctagon = n == 1)
    val found       = new ConcurrentHashMap[String, Set[VertexSignature]]()
    val states      = new AtomicLong(0)
    val done        = new AtomicLong(0)
    val capped      = new AtomicLong(0)
    // Per-Λ search bounds, tunable via system properties for higher n (larger cells need more head-room):
    //   `krot.percap` — max growth states per lattice before giving up (a safety net; the scatter prune keeps
    //                   most lattices far below it);
    //   `krot.cells`  — grow a Λ-consistent patch up to this many covolumes. The union fan reconstruction needs
    //                   only ~1 cell plus a thin corona; growing further just burns states on scatter branches.
    val perCap      = sys.props.get("krot.percap").map(_.toInt).getOrElse(400)
    val growthCells = sys.props.get("krot.cells").map(_.toDouble).getOrElse(4.0)
    log(s"n=$n k=$k maxCovol=$maxCovolume: ${bases.size} candidate lattices")

    def runLattice(v: BigPoint, w: BigPoint): Unit =
      val covol   = v.cross(w).abs
      val visited = mutable.HashSet.empty[List[(Int, BigDecimal, BigDecimal)]]
      val stack   = mutable.Stack.empty[Tiling]
      var local   = 0
      polygonSides.foreach: sides =>
        val seed = TilingBuilder.createRegularPolygon(RegularPolygon(sides))
        if LatticeConsistency.isConsistent(seed, v, w, seed.vertices.head.coords) then stack.push(seed)
      while stack.nonEmpty && local < perCap do
        val patch    = stack.pop()
        states.incrementAndGet()
        local += 1
        val origin   = patch.vertices.head.coords
        val area     = patch.innerFaces.map(_.areaUnsafe).sum
        // Keep each fixed-Λ patch to ~1 fundamental cell of DISTINCT content. The distinct-torus-face area
        // (faces counted once per position mod Λ) equals one covolume exactly when the patch covers a cell;
        // crucially it stays at one covolume as a genuinely Λ-periodic patch grows (new faces are translates),
        // but exceeds it the moment a non-Λ-periodic ("scatter") face is added. So:
        //   • distinct < covol  → not a full cell yet, grow;
        //   • distinct ≈ covol  → verify on the torus; if the fans aren't yet complete, grow a little more
        //                          (the union reconstruction needs ~1 cell plus a thin corona);
        //   • distinct > covol  → this branch is not Λ-periodic, PRUNE it (the key scatter cut — wrong-Λ
        //                          patches die here instead of growing to the cap).
        val distinct =
          if area >= covol - 1e-6 then distinctTorusFaceArea(patch, v, w, origin) else BigDecimal(0)
        if distinct > covol + BigDecimal("1e-6") then ()
        else if area >= covol - 1e-6 && distinct >= covol - 1e-6 then
          verifyTorus(patch, v, w, origin, n) match
            case Some((types, key)) => found.putIfAbsent(key, types): Unit
            case None               => if area < covol * growthCells then grow(patch, v, w, origin, n, visited, stack)
        else if area < covol * growthCells then grow(patch, v, w, origin, n, visited, stack)
      if local >= perCap then capped.incrementAndGet()
      val d       = done.incrementAndGet()
      if d % 500 == 0 then
        log(s"  lattices ${d}/${bases.size}, states=${states.get}, found=${found.size}, capped=${capped.get}")

    if parallelism <= 1 then bases.foreach(runLattice)
    else
      val pool = java.util.concurrent.Executors.newFixedThreadPool(parallelism)
      try bases.foreach((v, w) => pool.submit(new Runnable { def run(): Unit = runLattice(v, w) }))
      finally
        pool.shutdown()
        pool.awaitTermination(7, java.util.concurrent.TimeUnit.DAYS)
    log(s"  capped lattices (hit ${perCap} states): ${capped.get}")

    Outcome(found.asScala.toList.map((key, types) => (types, key)).sortBy(_._2), bases.size, states.get)

  private def fracOf(x: BigDecimal): BigDecimal =
    val r = x.setScale(9, BigDecimal.RoundingMode.HALF_UP)
    val f = r - r.setScale(0, BigDecimal.RoundingMode.FLOOR)
    if f >= BigDecimal(1) then BigDecimal(0).setScale(9) else f.setScale(9, BigDecimal.RoundingMode.HALF_UP)

  /** Total area of the patch's inner faces taken once per torus position (size, centroid mod Λ). Equals one
    * covolume exactly when the patch covers a full fundamental cell of distinct faces.
    */
  private def distinctTorusFaceArea(
      patch: TilingDCEL,
      v: BigPoint,
      w: BigPoint,
      origin: BigPoint
  ): BigDecimal =
    val det = v.x * w.y - v.y * w.x
    patch.innerFaces
      .map: f =>
        val c = f.getVerticesUnsafe.map(_.coords).centroid
        val d = c - origin
        (
          (
            f.halfEdgesUnsafe.size,
            fracOf((d.x * w.y - w.x * d.y) / det),
            fracOf((v.x * d.y - d.x * v.y) / det)
          ),
          f.areaUnsafe
        )
      .distinctBy(_._1)
      .map(_._2)
      .sum

  /** Torus-native verification of a one-cell Λ-consistent patch, replacing the expensive planar replicate +
    * certify. Returns the canonical torus key and the vertex-type set when the patch is a valid Krotenheerdt
    * tiling: the distinct torus faces tile one cell, every torus vertex has a complete 360° valid fan, and
    * the vertex orbits (color refinement of the torus vertex graph) number exactly n with n distinct types.
    */
  private def verifyTorus(
      patch: TilingDCEL,
      v: BigPoint,
      w: BigPoint,
      origin: BigPoint,
      n: Int
  ): Option[(Set[VertexSignature], String)] =
    val det                             = v.x * w.y - v.y * w.x
    // Group vertices by position mod Λ at a coarse integer resolution that WRAPS: a vertex sitting on a cell
    // boundary has lattice coordinate ≈ 0 or ≈ 1 (e.g. 0.9999998 vs 0.0000002 under Double-Λ rounding), which
    // `fracOf` would split into two classes; rounding to 1e5 and taking mod folds both to the same key, so the
    // two hexagon-cell vertices group into 2 classes, not 7. Vertices land on corners; faces sit mid-cell.
    def tkey(p: BigPoint): (Long, Long) =
      val d                         = p - origin
      def snap(t: BigDecimal): Long =
        val r = (t * 100000).setScale(0, BigDecimal.RoundingMode.HALF_UP).toBigInt
        (((r % 100000) + 100000) % 100000).toLong
      (snap((d.x * w.y - w.x * d.y) / det), snap((v.x * d.y - d.x * v.y) / det))

    def angleOf(d: BigPoint): Double = math.atan2(d.y.toDouble, d.x.toDouble)

    // Torus vertices: group planar vertices by position mod Λ. A torus vertex's full corona is split across its
    // planar instances (each carries the partial fan on its grown side); reconstruct it by unioning the
    // incident corners over all instances. Corners are keyed by ANGLE around the vertex, NOT by face identity
    // mod Λ: in a single-face cell (the hexagon's one hexagon/cell) the three faces around a vertex are all
    // translates of the same face (one mod-Λ identity), so identity-dedup would collapse the fan to one corner
    // — but each sits at a distinct angle. The corner angle is translation-invariant, so the partial fans
    // across all instances union into one full fan. This needs only ~1 grown cell, not a full planar corona.
    val byTorus = patch.vertices.groupBy(vertex => tkey(vertex.coords))

    // tk -> reconstructed fan as angularBucket -> face size.
    val torusFan = byTorus.view.mapValues: instances =>
      instances
        .flatMap: vx =>
          vx.incidentEdgesUnsafe
            .flatMap(_.incidentFace)
            .filter(_ != patch.outerFace)
            .distinct
            .map: f =>
              val c = f.getVerticesUnsafe.map(_.coords).centroid
              (math.round(angleOf(c - vx.coords) * 10000), f.halfEdgesUnsafe.size)
        .toMap
    .toMap

    def fanSignature(fan: Map[Long, Int]): VertexSignature =
      VertexTypes.normalize(fan.toList.sortBy(_._1).map(_._2))
    def fanComplete(fan: Map[Long, Int]): Boolean          =
      fan.values.map(interiorAngle).foldLeft(AngleDegree(0))(_ + _) == AngleDegree(360)

    if torusFan.exists((_, f) => !fanComplete(f)) then None
    else
      val sigs  = torusFan.view.mapValues(fanSignature).toMap
      val types = sigs.values.toSet
      if types.sizeIs != n then None
      else
        val faces    = patch.innerFaces
          .map(f => (f.halfEdgesUnsafe.size, f.getVerticesUnsafe.map(_.coords).centroid))
          .distinctBy((s, c) => (s, tkey(c)))
        // Key on the content's PRIMITIVE lattice (not the candidate Λ, which may be a proper sublattice):
        // a sublattice cell would otherwise key as an m-times-larger torus and duplicate the same tiling found
        // under its primitive lattice. primitiveBasis recovers it from the content's own periods.
        val (pv, pw) = primitiveBasis(v, w, origin, faces)
        // Iterate `sigs` as a list: mapping the Map to (signatureString, coords) pairs would rebuild a Map keyed
        // by the signature and collapse all same-type torus vertices (e.g. the snub's six 3.3.3.3.6 vertices)
        // into one, losing the chiral vertex positions and double-counting mirror images.
        val verts    = sigs.toList.map((tk, sig) => (sig.mkString("."), byTorus(tk).head.coords))
        // Rigorous vertex-orbit count on the primitive cell. 1-WL colour refinement only LOWER-bounds the orbit
        // count — it merges genuinely distinct orbits whose local neighbourhoods are isomorphic (the four
        // 3.3.3.3.6 vertices of the 3.3.3.3.6/3.6.3.6 pseudo-tiling look identical to 1-WL but split 2+2), which
        // would wrongly accept a 3-uniform tiling as 2-uniform. Instead count orbits exactly.
        val orbits   = vertexOrbits(pv, pw, faces, verts)
        if orbits != n then None
        else Some((types, torusContentKey(pv, pw, origin, faces, verts)))

  /** The primitive lattice of a cell's content, of any sublattice index. Candidate periods are the
    * differences of same-type face centroids (plus the candidate basis v0, w0), kept iff they preserve the
    * content mod Λ; the two shortest independent ones, Gauss-reduced, are the primitive basis. Handles any
    * index (not just the doubled case), so the key of every sublattice cell collapses to the primitive one.
    */
  private def primitiveBasis(
      v0: BigPoint,
      w0: BigPoint,
      origin: BigPoint,
      faces: List[(Int, BigPoint)]
  ): (BigPoint, BigPoint) =
    val det0                                      = v0.x * w0.y - v0.y * w0.x
    def tk(p: BigPoint): (BigDecimal, BigDecimal) =
      val d = p - origin
      (fracOf((d.x * w0.y - w0.x * d.y) / det0), fracOf((v0.x * d.y - d.x * v0.y) / det0))
    val content                                   = faces.map((s, c) => (s, tk(c))).toSet
    def isPeriod(t: BigPoint): Boolean            =
      faces.map((s, c) => (s, tk(c + t))).toSet == content
    // A finer (sub-Λ) period is no longer than the longer candidate basis vector (it spans the primitive cell
    // together with one basis vector); bounding candidates by that length keeps the check cheap on primitive
    // cells yet still catches every sublattice period — including one equal in length to the shorter basis
    // vector (a 2×1 sublattice of 4⁴, whose primitive period (1,0) equals |w0|), which a `min` bound misses.
    val maxLen2                                   = math.max(v0.dot(v0).toDouble, w0.dot(w0).toDouble)
    val shortPeriods                              =
      (for (s1, c1) <- faces; (s2, c2) <- faces if s1 == s2 yield c2 - c1)
        .filterNot(_.almostEquals(BigPoint.origin))
        .filter(d => d.dot(d).toDouble <= maxLen2 + 1e-6)
        .distinctBy(d =>
          (d.x.setScale(6, BigDecimal.RoundingMode.HALF_UP), d.y.setScale(6, BigDecimal.RoundingMode.HALF_UP))
        )
        .filter(isPeriod)
        .sortBy(p => p.dot(p))
    shortPeriods.headOption match
      case None     => gaussReducedSafe(v0, w0)
      case Some(pv) =>
        (shortPeriods ++ List(v0, w0)).find(p => (pv.x * p.y - pv.y * p.x).abs > BigDecimal("1e-6")) match
          case Some(pw) => gaussReducedSafe(pv, pw)
          case None     => gaussReducedSafe(v0, w0)

  /** Point-group frames of the lattice (v, w): basis pairs (a, b) — small integer combinations of v, w —
    * whose Gram matrix equals that of (v, w), i.e. the isometries (rotations and reflections, det = ±det0)
    * that map the lattice to itself. These, NOT all equal-covolume frames, are the linear parts of the
    * tiling's possible symmetries; a non-isometric equal-covolume frame is a shear, which is not a
    * congruence.
    */
  private def pointGroupFrames(v: BigPoint, w: BigPoint): List[(BigPoint, BigPoint)] =
    val (gvv, gww, gvw)                             = (v.dot(v), w.dot(w), v.dot(w))
    def near(a: BigDecimal, b: BigDecimal): Boolean = (a - b).abs < BigDecimal("1e-6")
    val combos                                      =
      for i <- -2 to 2; j <- -2 to 2 if i != 0 || j != 0
      yield BigPoint(i * v.x + j * w.x, i * v.y + j * w.y)
    for
      a <- combos.toList
      b <- combos
      if (near(a.dot(a), gvv) && near(b.dot(b), gww) && near(a.dot(b), gvw)) ||
        (near(a.dot(a), gww) && near(b.dot(b), gvv) && near(a.dot(b), gvw))
    yield (a, b)

  /** Exact number of vertex orbits of the (primitive) cell content under the tiling's symmetry group. Two
    * cell vertices are in the same orbit iff the whole content rooted at one (that vertex translated to the
    * origin) maps onto the content rooted at the other under a lattice isometry ([[pointGroupFrames]]) — i.e.
    * their canonical rooted fingerprints (min over point-group frames) coincide. This is exact, unlike 1-WL
    * colour refinement which only lower-bounds the orbit count and so can pass a > n-uniform tiling as
    * n-uniform.
    */
  private def vertexOrbits(
      v: BigPoint,
      w: BigPoint,
      faces: List[(Int, BigPoint)],
      verts: List[(String, BigPoint)]
  ): Int =
    val frames                           = pointGroupFrames(v, w)
    def rootedKey(org: BigPoint): String =
      frames
        .map: (a, b) =>
          val det                                        = a.x * b.y - a.y * b.x
          def lat(p: BigPoint): (BigDecimal, BigDecimal) =
            val d = p - org
            (fracOf((d.x * b.y - b.x * d.y) / det), fracOf((a.x * d.y - d.x * a.y) / det))
          val fs                                         = faces.map { (s, c) =>
            val (x, y) = lat(c); s"$s:$x:$y"
          }.sorted
          val vs                                         = verts.map { (t, c) =>
            val (x, y) = lat(c); s"$t:$x:$y"
          }.sorted
          (fs ++ vs).mkString("|")
        .min
    verts.map((_, c) => rootedKey(c)).toSet.size

  /** Canonical key of one fundamental cell's content under all equivalent bases and cell origins. Assumes the
    * passed (v, w) is already the primitive basis (see [[primitiveBasis]]). Reflection-invariant: the frame
    * (a, b) ranges over all small integer combinations of the basis with covolume det = ±det0 — a NEGATIVE
    * determinant is a left-handed (reflected) coordinate frame, so a chiral tiling and its mirror, counted
    * once under the up-to-all-isometries convention (the snub `3.3.3.3.6`; `3.12.12 + 3.4.3.12` at n=2),
    * collapse to one key. The −2..2 combination range is wide enough to realise every lattice automorphism
    * relating the two chiralities (the hexagonal lattice's are not all reached by `{v, w, v±w}` alone).
    */
  private def torusContentKey(
      v: BigPoint,
      w: BigPoint,
      origin: BigPoint,
      faces: List[(Int, BigPoint)],
      verts: List[(String, BigPoint)]
  ): String =
    val det0       = (v.x * w.y - v.y * w.x).abs
    val candidates =
      for i <- -2 to 2; j <- -2 to 2 if i != 0 || j != 0
      yield BigPoint(i * v.x + j * w.x, i * v.y + j * w.y)
    val keys       =
      for
        a  <- candidates
        b  <- candidates
        det = a.x * b.y - a.y * b.x
        if (det.abs - det0).abs < BigDecimal("1e-9")
      yield
        def lat(p: BigPoint): (BigDecimal, BigDecimal) =
          val d = p - origin
          ((d.x * b.y - b.x * d.y) / det, (a.x * d.y - d.x * a.y) / det)
        val fs                                         = faces.map((s, c) => (s, lat(c)))
        val vs                                         = verts.map((t, c) => (t, lat(c)))
        fs.map(_._2).distinct.map: (oa, ob) =>
          val f = fs.map((s, ab) => (s, fracOf(ab._1 - oa), fracOf(ab._2 - ob))).distinct.sorted
          val u = vs.map((t, ab) => (t, fracOf(ab._1 - oa), fracOf(ab._2 - ob))).distinct.sorted
          (f.map((s, x, y) => s"$s:$x:$y") ++ u.map((t, x, y) => s"$t:$x:$y")).mkString("|")
        .min
    keys.min

  /** Push every Λ-consistent, sound continuation that fills the centroid-nearest boundary gap. */
  private def grow(
      patch: Tiling,
      v: BigPoint,
      w: BigPoint,
      origin: BigPoint,
      n: Int,
      visited: mutable.HashSet[List[(Int, BigDecimal, BigDecimal)]],
      stack: mutable.Stack[Tiling]
  ): Unit =
    val gaps     = patch.boundaryVerticesUnsafe.flatMap: vertex =>
      val gap = AngleDegree(360) - vertex.currentInteriorAngleSumUnsafe(patch.outerFace)
      Option.when(gap.toRational > 0)((vertex, gap))
    val centroid = patch.vertices.map(_.coords).centroid
    gaps.minByOption((vertex, gap) =>
      (vertex.coords.distanceTo(centroid), gap.toRational, vertex.id.value)
    ).foreach: (target, gap) =>
      val previousInnerIds = patch.innerVertices.map(_.id).toSet
      polygonSides.foreach: sides =>
        if interiorAngle(sides).toRational <= gap.toRational then
          patch
            .maybeAddRegularPolygonToBoundary(target.id, RegularPolygon(sides))
            .toOption
            .filter(next =>
              isSound(next, previousInnerIds, n) && LatticeConsistency.isConsistent(next, v, w, origin)
            )
            .foreach: next =>
              if visited.add(PatchCanonical.congruenceKey(next)) then stack.push(next)

  private def isSound(next: Tiling, previousInnerIds: Set[structure.VertexId], n: Int): Boolean =
    val newInnerValid =
      next.innerVertices
        .filterNot(v => previousInnerIds.contains(v.id))
        .forall(v => isCompleteVertex(vertexTypeOf(next, v)))
    val fansValid     =
      next.boundaryVerticesUnsafe.forall: vertex =>
        boundaryFan(next, vertex) match
          case Nil => true
          case fan => isExtendableFan(fan)
    next.hasUnitRegularPolygonsOnly && newInnerValid && fansValid && innerVertexTypes(next).sizeIs <= n

  private def boundaryFan(tiling: TilingDCEL, vertex: structure.Vertex): List[Int] =
    val edges      = vertex.incidentEdgesUnsafe
    val outerIndex = edges.indexWhere(_.incidentFace.exists(_ eq tiling.outerFace))
    val ordered    = if outerIndex < 0 then edges else edges.startAt(outerIndex).tail
    ordered.flatMap(_.incidentFace).filter(_ != tiling.outerFace).map(_.halfEdgesUnsafe.size)
