package io.github.scala_tessella.dcel

import io.github.scala_tessella.dcel.DelaneySymbols.{DSet, DSymbol}
import io.github.scala_tessella.dcel.VertexTypes.{VertexSignature, normalize}
import org.sat4j.core.VecInt
import org.sat4j.minisat.SolverFactory
import org.sat4j.specs.ContradictionException

import scala.collection.mutable

/** Per-type-set Delaney-symbol assembly by SAT (ADR-0039 Phase 2, SAT4J baseline).
  *
  * A Krotenheerdt n-uniform tiling's minimal symbol decomposes into n vertex STARS — the `(1,2)`-orbits,
  * whose internal structure (σ₁, σ₂, m₀₁) is fully determined by the vertex TYPE and a FOLDING (the vertex
  * stabilizer: a subgroup of the figure's dihedral symmetry). Only σ₀ (which chamber lies across each edge)
  * is unknown. So, per candidate type-set (from [[TypeCompatibility.candidates]]) and folding choice, the
  * enumeration is: all involutions σ₀ satisfying
  *
  *   - m₀₁-equality (σ₀ keeps the face, so the polygon size matches),
  *   - σ₂-equivariance ((σ₀σ₂)² = id — the two-faces-per-edge D-set axiom),
  *   - face closure ((σ₀σ₁)^p = id at every chamber of polygon size p ⟺ every face orbit's r₀₁ divides p),
  *
  * enumerated by a CDCL solver (SAT4J `ModelIterator`), then classified by the EXISTING oracle tail —
  * `isEuclidean`, `regularPolygonVertices`, `isMinimal`, `canonicalKey` — so results dedup in the shared key
  * space and soundness is inherited, not re-implemented. By the 12n bound (ADR-0039) this search space
  * contains every tiling of the set; non-minimal solutions are duplicates of more-folded assemblies and are
  * discarded, so completeness per (set, foldings-swept) holds while dedup stays exact.
  */
object SymbolAssembly:

  // ---- the star model (chambers 0-based INSIDE a star) -------------------------------------------------

  /** A 12-orbit candidate: σ₁/σ₂ internal involutions (fixed point stored as self), per-chamber polygon size,
    * and the geometric vertex degree (= m₁₂, regardless of folding).
    */
  final case class Star(s1: Vector[Int], s2: Vector[Int], m01: Vector[Int], degree: Int):
    def size: Int = m01.size

  /** The UNFOLDED star of a vertex type (trivial stabilizer): `2d` chambers, two per corner — chamber `2i`
    * and `2i+1` sit in corner `i` (face of `sig(i)` sides), σ₁ pairs the corner's two chambers, σ₂ crosses
    * the edge between consecutive corners.
    */
  def unfoldedStar(sig: VertexSignature): Star =
    val d = sig.size
    val n = 2 * d
    Star(
      s1 = Vector.tabulate(n)(j => if j % 2 == 0 then j + 1 else j - 1),
      s2 = Vector.tabulate(n)(j => if j % 2 == 0 then (j - 1 + n) % n else (j + 1) % n),
      m01 = Vector.tabulate(n)(j => sig(j / 2)),
      degree = d
    )

  /** The symmetries of the figure acting on the unfolded star's chambers: the rotations and reflections of
    * the `2d`-cycle that preserve σ₁/σ₂ structure (they do by shape) AND the m₀₁ labels. Reflections pass
    * through a corner's σ₁-edge or an edge's σ₂-pair, so the action on CHAMBERS is free. Closed under
    * composition by construction (m₀₁-preserving maps compose).
    */
  def starSymmetries(sig: VertexSignature): Vector[Vector[Int]] =
    val star = unfoldedStar(sig)
    val n    = star.size
    val rots = (0 until sig.size).map(k => Vector.tabulate(n)(j => (j + 2 * k) % n))
    val refl = (0 until sig.size).flatMap: a =>
      List(
        Vector.tabulate(n)(j => ((4 * a + 1 - j) % n + n) % n), // axis through corner a's σ₁-edge
        Vector.tabulate(n)(j => ((4 * a + 3 - j) % n + n) % n) // axis through the σ₂-edge after corner a
      )
    (rots ++ refl).filter(p => (0 until n).forall(j => star.m01(p(j)) == star.m01(j))).distinct.toVector

  /** All subgroups of the (dihedral-or-cyclic, order ≤ 24) symmetry group — every subgroup of a dihedral
    * group is generated by at most two elements, so closing all generator pairs is exhaustive.
    */
  private def subgroups(group: Vector[Vector[Int]]): Set[Set[Vector[Int]]] =
    def compose(a: Vector[Int], b: Vector[Int]): Vector[Int] = Vector.tabulate(a.size)(j => a(b(j)))
    def close(gens: Set[Vector[Int]]): Set[Vector[Int]]      =
      var s       = gens + group.head.indices.toVector // identity
      var changed = true
      while changed do
        val next = s ++ (for a <- s; b <- s yield compose(a, b))
        changed = next.size != s.size
        s = next
      s
    (for a <- group; b <- group yield close(Set(a, b))).toSet

  /** Quotient the unfolded star by a stabilizer subgroup `h`: chambers = orbits, σ̄ᵢ = induced involutions
    * (an orbit mapped to itself by σᵢ becomes a FIXED point — a chain end at a mirror).
    */
  private def quotientStar(sig: VertexSignature, h: Set[Vector[Int]]): Star =
    val star                    = unfoldedStar(sig)
    val n                       = star.size
    val orbitOf                 = Array.fill(n)(-1)
    var count                   = 0
    for j <- 0 until n if orbitOf(j) < 0 do
      for g <- h do orbitOf(g(j)) = count
      count += 1
    def induced(s: Vector[Int]) = Vector.tabulate(count) { c =>
      val j = orbitOf.indexOf(c)
      orbitOf(s(j))
    }
    Star(
      induced(star.s1),
      induced(star.s2),
      Vector.tabulate(count)(c => star.m01(orbitOf.indexOf(c))),
      sig.size
    )

  /** A canonical walk-key for a star: the σ₁/σ₂-alternating walk visits the whole orbit (cycle or bouncing
    * chain); minimising the recorded `(m₀₁, fixed?)` trace over every start chamber and first-op choice gives
    * a label-free invariant — equal keys ⟺ isomorphic stars. Used for folding dedup AND the oracle fixture
    * match.
    */
  def canonicalStarKey(star: Star): String =
    val n                                      = star.size
    def walk(start: Int, firstOp: Int): String =
      val sb  = new StringBuilder(s"d${star.degree}:")
      var cur = start
      var op  = firstOp
      for _ <- 0 until 2 * n do
        val nxt = if op == 1 then star.s1(cur) else star.s2(cur)
        // record WHICH σ was applied: a σ₁-fixed end (mirror through the face corner) and a σ₂-fixed end
        // (mirror along the edge) are structurally DIFFERENT stars — an op-blind trace conflated the two
        // 4-chain foldings of 4⁴ and silently dropped one (the G2 19/20 bug)
        sb.append(star.m01(cur)).append(op).append(if nxt == cur then 'F' else '-')
        cur = nxt
        op = 3 - op
      sb.toString
    (for start <- 0 until n; op <- 1 to 2 yield walk(start, op)).min

  /** Every legal folded star of a type — one per stabilizer subgroup, deduped up to isomorphism. Contains the
    * unfolded star (trivial subgroup) always; the fully-folded one when the figure is fully symmetric.
    */
  def starFoldings(sig: VertexSignature): Vector[Star] =
    subgroups(starSymmetries(sig)).toVector
      .map(h => quotientStar(sig, h))
      .distinctBy(canonicalStarKey)

  /** The stars a REAL symbol is made of: each `(1,2)`-orbit with its induced σ₁/σ₂/m₀₁, locally reindexed.
    * The oracle fixture test checks every induced star is (isomorphic to) one of [[starFoldings]] for its
    * type — the completeness direction of the star model.
    */
  def inducedStars(ds: DSymbol): Vector[Star] =
    ds.orbs
      .filter(o => o.i == 1 && o.j == 2)
      .map { o =>
        val idx = o.elements.zipWithIndex.toMap
        Star(
          s1 = o.elements.map(d => idx(ds.get(1, d))),
          s2 = o.elements.map(d => idx(ds.get(2, d))),
          m01 = o.elements.map(d => ds.m(0, 1, d)),
          degree = ds.m(1, 2, o.elements.head)
        )
      }

  /** All structure-preserving self-maps of a (folded) star — σ₁/σ₂/m₀₁-preserving chamber permutations. The
    * star is σ₁σ₂-connected, so a map is FORCED by the image of chamber 0 (propagate `map(σᵢx) = σᵢ(map x)`);
    * at most `size` candidates, each kept iff propagation is consistent and m₀₁-preserving. Rotations AND
    * reflections both arise this way. Used as SAT symmetry-breaking targets (ADR-0041).
    */
  def starAutomorphisms(star: Star): Vector[Vector[Int]] =
    val n = star.size
    (0 until n).toVector.flatMap: c0 =>
      val map  = Array.fill(n)(-1)
      map(0) = c0
      var ok   = true
      val todo = mutable.Queue(0)
      while todo.nonEmpty && ok do
        val x = todo.dequeue()
        if star.m01(map(x)) != star.m01(x) then ok = false
        else
          for (sx, smx) <- List((star.s1(x), star.s1(map(x))), (star.s2(x), star.s2(map(x)))) do
            if map(sx) < 0 then
              map(sx) = smx
              todo.enqueue(sx)
            else if map(sx) != smx then ok = false
      if ok && map.forall(_ >= 0) then Some(map.toVector) else None

  // ---- σ₀ constraint predicates (shared by the oracle FIXTURE tests and the post-solve assertions) -----

  /** The three σ₀ requirements over global 1-based arrays (σ fixed points stored as self). Every euclidean
    * regular-polygon D-symbol satisfies them (tested against the oracle), and together with the star
    * structure they are exactly what the SAT instance encodes.
    */
  def sigma0Valid(
      s0: IndexedSeq[Int],
      s1: IndexedSeq[Int],
      s2: IndexedSeq[Int],
      m01: IndexedSeq[Int]
  ): Boolean =
    val m          = s0.size - 1
    def involution = (1 to m).forall(c => s0(c) >= 1 && s0(c) <= m && s0(s0(c)) == c)
    def faceSize   = (1 to m).forall(c => m01(s0(c)) == m01(c))
    def sigma2Eq   = (1 to m).forall(c => s0(s2(s0(s2(c)))) == c)
    def faces      = (1 to m).forall: c =>
      var cur = c
      for _ <- 1 to m01(c) do cur = s0(s1(cur))
      cur == c
    involution && faceSize && sigma2Eq && faces

  // ---- the SAT instance -----------------------------------------------------------------------------

  /** One assembly frame: the chosen folded stars laid out on global chambers `1..size`. */
  final case class Frame(stars: Vector[Star]):
    val offsets: Vector[Int]  = stars.scanLeft(1)(_ + _.size)
    val size: Int             = offsets.last - 1
    val s1: Vector[Int]       = Vector.tabulate(size + 1)(identity).map { c =>
      if c == 0 then 0
      else
        val k = stars.indices.find(i => c < offsets(i + 1)).get
        stars(k).s1(c - offsets(k)) + offsets(k)
    }
    val s2: Vector[Int]       = Vector.tabulate(size + 1)(identity).map { c =>
      if c == 0 then 0
      else
        val k = stars.indices.find(i => c < offsets(i + 1)).get
        stars(k).s2(c - offsets(k)) + offsets(k)
    }
    val m01: Vector[Int]      = Vector.tabulate(size + 1) { c =>
      if c == 0 then 0
      else
        val k = stars.indices.find(i => c < offsets(i + 1)).get
        stars(k).m01(c - offsets(k))
    }
    val degreeOf: Vector[Int] = Vector.tabulate(size + 1) { c =>
      if c == 0 then 0
      else stars(stars.indices.find(i => c < offsets(i + 1)).get).degree
    }
    val starOf: Vector[Int]   = Vector.tabulate(size + 1) { c =>
      if c == 0 then -1
      else stars.indices.find(i => c < offsets(i + 1)).get
    }

  /** All σ₀ involutions of the frame satisfying the three constraints, via SAT4J CDCL + `ModelIterator`.
    * Variables: one per unordered chamber pair (self allowed) with equal m₀₁; exactly-one per chamber; binary
    * σ₂-equivariance clauses; face closure by a one-hot (σ₀σ₁)-path per σ₁-representative chamber (layer k =
    * position after k steps; unit-forced back to the start at layer p). `maxModels` is a flood-guard — a
    * capped result is reported, never silent.
    */
  def enumerateSigma0(
      frame: Frame,
      maxModels: Int = 20000,
      symmetries: Vector[Vector[Int]] = Vector.empty
  ): (List[Array[Int]], Boolean) =
    val m                               = frame.size
    val pairs                           =
      for
        a <- 1 to m
        b <- a to m
        if frame.m01(a) == frame.m01(b)
      yield (a, b)
    val pairVar                         = pairs.zipWithIndex.map((p, i) => p -> (i + 1)).toMap
    def pv(a: Int, b: Int): Option[Int] = pairVar.get(if a <= b then (a, b) else (b, a))
    var nextVar                         = pairs.size

    // clauses are STREAMED into the solver as generated — buffering them OOM'd on n=4-sized frames.
    // Enumeration is hand-rolled (NOT ModelIterator): blocking only the true σ₀ pair-variables keeps each
    // blocking clause ≤ #chambers wide; ModelIterator blocks the FULL model incl. thousands of face-path
    // auxiliaries, which OOM'd a 10g heap on the symmetric-rich n=5 sets (tens of thousands of models).
    val solver = SolverFactory.newDefault()
    solver.setTimeout(3600)
    val out    = mutable.ListBuffer.empty[Array[Int]]
    var capped = false
    try
      def clause(lits: Int*): Unit         = solver.addClause(new VecInt(lits.toArray))
      def exactly1(lits: Array[Int]): Unit = solver.addExactly(new VecInt(lits), 1)

      // exactly one partner per chamber
      for c <- 1 to m do exactly1((1 to m).flatMap(d => pv(c, d)).toArray)
      // σ₂-equivariance: σ₀(a)=b ⇒ σ₀(σ₂(a))=σ₂(b)
      for ((a, b), v) <- pairVar do
        pv(frame.s2(a), frame.s2(b)) match
          case Some(w) => if w != v then clause(-v, w)
          case None    => clause(-v)
      // star-cut connectivity: a real tiling is connected and stars are internally σ₁σ₂-connected, so every
      // proper star-cut must be crossed by some σ₀ pair. Kills the DISCONNECTED product solutions that
      // flooded the symmetric n=5 sets with 10⁵+ models (an empty cut clause = the frame is unrealizable).
      val k = frame.stars.size
      if k >= 2 then
        for mask <- 0 until ((1 << (k - 1)) - 1) do
          def inS(i: Int) = i == 0 || ((mask >> (i - 1)) & 1) == 1
          clause(pairVar.collect {
            case ((a, b), v) if inS(frame.starOf(a)) != inS(frame.starOf(b)) => v
          }.toSeq*)
      // face closure: for each σ₁-representative c with p = m₀₁(c), the (σ₀σ₁)-path returns to c at step p
      for c <- 1 to m if c <= frame.s1(c) do
        val p      = frame.m01(c)
        val domain = (1 to m).filter(d => frame.m01(d) == p).toArray
        val y      = Array.tabulate(p + 1)(_ => mutable.Map.empty[Int, Int]) // layer -> chamber -> var
        for k <- 1 to p; d <- domain do
          nextVar += 1
          y(k)(d) = nextVar
        // layer 1 ⇔ σ₀(σ₁(c)): x(σ₁(c),d) → y(1,d)
        for d <- domain do pv(frame.s1(c), d).foreach(x => clause(-x, y(1)(d)))
        // transitions: y(k,d) ∧ x(σ₁(d),d') → y(k+1,d')
        for k <- 1 until p; d <- domain; d2 <- domain do
          pv(frame.s1(d), d2).foreach(x => clause(-y(k)(d), -x, y(k + 1)(d2)))
        for k <- 1 to p do exactly1(domain.map(y(k)))
        clause(y(p)(c))

      // symmetry breaking (ADR-0041): each π is a constraint symmetry of the x-projection (star
      // automorphism / identical-star swap), so requiring x ≤lex x∘π (fixed pair-var order, eq-prefix
      // chain) keeps at least the orbit-lex-min of every solution class — sound, kills swap floods
      for pi <- symmetries do
        def img(c: Int) = pi(c)
        var ePrev       = 0 // 0 = "prefix equal" is vacuously true so far
        for (pr, v) <- pairs.map(pr => pr -> pairVar(pr)) do
          val (a, b) = pr
          val w      = pv(img(a), img(b)).getOrElse(0)
          if w != 0 && w != v then
            // prefix-equal ∧ x_v → x_w  (forbid first-difference 1→0)
            if ePrev == 0 then clause(-v, w) else clause(-ePrev, -v, w)
            nextVar += 1
            val e = nextVar
            if ePrev == 0 then
              clause(-e, -v, w); clause(-e, v, -w); clause(-v, -w, e); clause(v, w, e)
            else
              clause(-e, ePrev); clause(-e, -v, w); clause(-e, v, -w)
              clause(-ePrev, -v, -w, e); clause(-ePrev, v, w, e)
            ePrev = e

      var go = true
      while go && out.size <= maxModels && solver.isSatisfiable do
        val model  = solver.model()
        val trues  = model.filter(_ > 0).toSet
        val s0     = Array.fill(m + 1)(0)
        val chosen = mutable.ArrayBuffer.empty[Int]
        for ((a, b), v) <- pairVar if trues(v) do
          s0(a) = b
          s0(b) = a
          chosen += v
        out += s0
        // block THIS σ₀ (a distinct one must flip at least one chosen pair); adding may hit contradiction
        try solver.addClause(new VecInt(chosen.map(-_).toArray))
        catch case _: ContradictionException => go = false
    catch case _: ContradictionException => () // trivially UNSAT
    if out.size > maxModels then
      capped = true
      out.dropRightInPlace(out.size - maxModels)
    (out.toList, capped)

  // ---- classify (the EXISTING oracle tail — soundness inherited, shared key space) --------------------

  /** Build the D-symbol of a solved frame and run the oracle filters. Returns the canonical key when the
    * assembly is a connected, euclidean, MINIMAL regular-polygon symbol realizing exactly the frame's types
    * (non-minimal solutions are duplicates of a more-folded assembly and are dropped).
    */
  def classify(frame: Frame, s0: Array[Int]): Option[(String, DSymbol)] =
    val m    = frame.size
    val op   = Array.ofDim[Int](m + 1, 3)
    for c <- 1 to m do
      op(c)(0) = s0(c)
      op(c)(1) = frame.s1(c)
      op(c)(2) = frame.s2(c)
    val dset = new DSet(op)
    // connected?
    val seen = mutable.Set(1)
    val todo = mutable.Queue(1)
    while todo.nonEmpty do
      val c = todo.dequeue()
      for i <- 0 to 2 do
        val d = dset.get(i, c)
        if d >= 1 && !seen(d) then { seen += d; todo.enqueue(d) }
    if seen.size != m then None
    else
      val (orbs, index) = DelaneySymbols.collectOrbits(dset)
      val vs            = Array.ofDim[Int](orbs.size)
      var ok            = true
      for (o, i) <- orbs.zipWithIndex do
        val c    = o.elements.head
        val full = if o.i == 0 then frame.m01(c) else frame.degreeOf(c)
        // face/vertex order incompatible (the encoding guarantees faces; guard both anyway)
        if full % o.r != 0 then ok = false else vs(i) = full / o.r
      if !ok then None
      else
        val dsym = new DSymbol(dset, orbs, index, vs)
        if !DelaneySymbols.isEuclidean(dsym) then None
        else
          DelaneySymbols.regularPolygonVertices(dsym) match
            case Some(_) if DelaneySymbols.isMinimal(dsym) =>
              Some(DelaneySymbols.canonicalKey(dsym) -> dsym)
            case _                                         => None

  // ---- the per-type-set driver ------------------------------------------------------------------------

  final case class SetResult(tilings: Map[String, DSymbol], models: Int, capped: Boolean):
    def keys: Set[String] = tilings.keySet

  /** Non-decreasing k-selections from `xs` (combinations with repetition, by index). */
  private def combosWithRep[A](xs: Vector[A], k: Int): Vector[Vector[A]] =
    if k == 0 then Vector(Vector.empty)
    else xs.zipWithIndex.flatMap((x, i) => combosWithRep(xs.drop(i), k - 1).map(x +: _))

  /** ADR-0041: enumerate every tiling whose vertex-type MULTISET is exactly `types` — n orbits over
    * possibly-repeated types (m-Archimedean n-uniform; the Krotenheerdt case is the all-distinct special
    * case). One star per orbit; folding choices for IDENTICAL stars are swept as combinations-with-repetition
    * (frame-level swap dedup — permuting identical stars yields isomorphic frames). The sigma_0 enumeration
    * and classify tail are unchanged: classify never required distinct types, and a same-type orbit pair
    * merged by the true symmetry shows up as a NON-minimal symbol here (discarded) and as the minimal symbol
    * of the smaller multiset (counted there) — exactly the (n, m) bookkeeping the table needs.
    */
  def solveMultiset(types: Seq[VertexSignature], maxModels: Int = 20000): SetResult =
    val sorted                                                                   = types.map(normalize).toList.sortBy(s => (s.size, s.mkString(".")))
    val groups                                                                   = sorted.distinct.map(t => t -> sorted.count(_ == t))
    val perGroup                                                                 = groups.map((t, k) => combosWithRep(starFoldings(t), k)).toVector
    val tilings                                                                  = mutable.Map.empty[String, DSymbol]
    var models                                                                   = 0
    var capped                                                                   = false
    def frameSymmetries(frame: Frame, chosen: Vector[Star]): Vector[Vector[Int]] =
      val perStar = chosen.indices.toVector.flatMap: i =>
        val off = frame.offsets(i)
        starAutomorphisms(chosen(i)).filter(a => a != a.indices.toVector).map: a =>
          Vector.tabulate(frame.size + 1)(c =>
            if c >= off && c < off + chosen(i).size then a(c - off) + off else c
          )
      val swaps   = (0 until chosen.size - 1).toVector
        .filter(i =>
          canonicalStarKey(chosen(i)) == canonicalStarKey(chosen(i + 1)) && chosen(i) == chosen(i + 1)
        )
        .map: i =>
          val (o1, o2, sz) = (frame.offsets(i), frame.offsets(i + 1), chosen(i).size)
          Vector.tabulate(frame.size + 1)(c =>
            if c >= o1 && c < o1 + sz then c + sz else if c >= o2 && c < o2 + sz then c - sz else c
          )
      perStar ++ swaps
    def sweep(i: Int, chosen: Vector[Star]): Unit                                =
      if i == perGroup.size then
        val frame        = Frame(chosen)
        val (sols, capd) = enumerateSigma0(frame, maxModels, frameSymmetries(frame, chosen))
        capped |= capd
        models += sols.size
        sols.foreach(s0 => classify(frame, s0).foreach((k, sym) => tilings.getOrElseUpdate(k, sym)))
      else perGroup(i).foreach(fs => sweep(i + 1, chosen ++ fs))
    sweep(0, Vector.empty)
    SetResult(tilings.toMap, models, capped)

  /** Enumerate every tiling whose vertex-type set is exactly `ts` (all types distinct — the Krotenheerdt
    * case): [[solveMultiset]] with multiplicity 1 everywhere.
    */
  def solveTypeSet(ts: Set[VertexSignature], maxModels: Int = 20000): SetResult =
    solveMultiset(ts.toList, maxModels)

  /** ADR-0041 cell driver: all m-Archimedean n-uniform tilings — every fair support of size m (the ADR-0040
    * filters are multiplicity-blind necessities on the realized type SET) x every positive multiplicity
    * assignment summing to n. Cells are disjoint (a tiling's type multiset is intrinsic), so the table value
    * is the summed key count.
    */
  def solveCell(
      n: Int,
      m: Int,
      maxModels: Int = 20000,
      parallelism: Int = 1
  ): Map[List[VertexSignature], SetResult] =
    require(m >= 1 && n >= m, s"need 1 <= m <= n, got m=$m n=$n")
    def comps(total: Int, parts: Int): Vector[Vector[Int]] =
      if parts == 1 then Vector(Vector(total))
      else (1 to total - parts + 1).toVector.flatMap(h => comps(total - h, parts - 1).map(h +: _))
    val jobs                                               =
      for
        support <- TypeCompatibility.candidates(m).toVector
        order    = support.toVector.sortBy(s => (s.size, s.mkString(".")))
        c       <- comps(n, order.size)
      yield order.lazyZip(c).flatMap((t, k) => Vector.fill(k)(t)).toList
    def run(ms: List[VertexSignature])                     = ms -> solveMultiset(ms, maxModels)
    if parallelism <= 1 then jobs.map(run).toMap
    else
      val pool = java.util.concurrent.Executors.newFixedThreadPool(parallelism)
      try jobs.map(ms => pool.submit(() => run(ms))).map(_.get()).toMap
      finally pool.shutdown()

  /** The gate driver: solve every fair candidate type-set of size `n` (ADR-0040) and return the deduped
    * canonical keys — comparable key-for-key with `DelaneySymbols.keyedTilings`. Candidate sets are
    * independent, so `parallelism > 1` fans them over a fixed pool (each solve owns its solver; the shared
    * derivations are immutable). Keep pool x heap within the machine limits (31 GiB RAM, 1 GiB swap).
    */
  def enumerate(n: Int, maxModels: Int = 20000, parallelism: Int = 1): Map[Set[VertexSignature], SetResult] =
    val cands = TypeCompatibility.candidates(n).toVector
    if parallelism <= 1 then cands.map(ts => ts -> solveTypeSet(ts, maxModels)).toMap
    else
      val pool = java.util.concurrent.Executors.newFixedThreadPool(parallelism)
      try cands.map(ts => pool.submit(() => ts -> solveTypeSet(ts, maxModels))).map(_.get()).toMap
      finally pool.shutdown()
